-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.access_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  email text NOT NULL,
  empresa text NOT NULL,
  cargo text DEFAULT ''::text,
  telefone text DEFAULT ''::text,
  mensagem text DEFAULT ''::text,
  status text NOT NULL DEFAULT 'pendente'::text,
  motivo_recusa text DEFAULT ''::text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT access_requests_pkey PRIMARY KEY (id),
  CONSTRAINT access_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  nome text NOT NULL,
  segmento text NOT NULL DEFAULT 'Outro'::text,
  porte text NOT NULL DEFAULT 'PME'::text,
  contato_nome text NOT NULL DEFAULT ''::text,
  contato_cargo text NOT NULL DEFAULT ''::text,
  contato_email text NOT NULL DEFAULT ''::text,
  contato_whatsapp text NOT NULL DEFAULT ''::text,
  fluig_versao text NOT NULL DEFAULT ''::text,
  fluig_modulos ARRAY NOT NULL DEFAULT '{}'::text[],
  score_potencial integer NOT NULL DEFAULT 0,
  score_maturidade integer NOT NULL DEFAULT 0,
  score_dor integer NOT NULL DEFAULT 0,
  score_risco_churn integer NOT NULL DEFAULT 0,
  score_acesso integer NOT NULL DEFAULT 0,
  score_total integer NOT NULL DEFAULT 0,
  tier text NOT NULL DEFAULT 'C'::text,
  onda integer NOT NULL DEFAULT 3,
  observacoes text NOT NULL DEFAULT ''::text,
  criado_em timestamp with time zone NOT NULL DEFAULT now(),
  atualizado_em timestamp with time zone NOT NULL DEFAULT now(),
  data_registro date,
  data_proxima_visita date,
  data_ultimo_contato date,
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.opportunities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_id uuid NOT NULL,
  user_id uuid NOT NULL,
  estagio text NOT NULL DEFAULT 'selecionado'::text,
  mrr_estimado numeric NOT NULL DEFAULT 0,
  mrr_fechado numeric NOT NULL DEFAULT 0,
  pacote_works text NOT NULL DEFAULT 'Essencial'::text,
  data_contato text NOT NULL DEFAULT ''::text,
  data_visita text NOT NULL DEFAULT ''::text,
  data_proposta text NOT NULL DEFAULT ''::text,
  data_fechamento text NOT NULL DEFAULT ''::text,
  motivo_perda text NOT NULL DEFAULT ''::text,
  proximo_passo text NOT NULL DEFAULT ''::text,
  data_proximo_passo text NOT NULL DEFAULT ''::text,
  responsavel text NOT NULL DEFAULT 'Camila'::text,
  criado_em timestamp with time zone NOT NULL DEFAULT now(),
  atualizado_em timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT opportunities_pkey PRIMARY KEY (id),
  CONSTRAINT opportunities_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT opportunities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  nome text NOT NULL DEFAULT ''::text,
  email text NOT NULL DEFAULT ''::text,
  empresa text NOT NULL DEFAULT ''::text,
  cargo text DEFAULT ''::text,
  avatar_url text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  role text NOT NULL DEFAULT 'user'::text,
  ativado boolean NOT NULL DEFAULT true,
  telefone text DEFAULT ''::text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  visit_id uuid,
  account_id uuid NOT NULL,
  user_id uuid NOT NULL,
  tipo text NOT NULL DEFAULT 'Relatorio_Executivo'::text,
  titulo text NOT NULL DEFAULT ''::text,
  contexto_cliente text NOT NULL DEFAULT ''::text,
  dores_priorizadas text NOT NULL DEFAULT ''::text,
  impacto_estimado text NOT NULL DEFAULT ''::text,
  solucao_proposta text NOT NULL DEFAULT ''::text,
  entregaveis text NOT NULL DEFAULT ''::text,
  investimento_mrr numeric NOT NULL DEFAULT 0,
  prazo_implantacao text NOT NULL DEFAULT ''::text,
  status text NOT NULL DEFAULT 'Rascunho'::text,
  criado_em timestamp with time zone NOT NULL DEFAULT now(),
  atualizado_em timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT reports_visit_id_fkey FOREIGN KEY (visit_id) REFERENCES public.visits(id),
  CONSTRAINT reports_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.visits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  opportunity_id uuid NOT NULL,
  account_id uuid NOT NULL,
  user_id uuid NOT NULL,
  data_visita text NOT NULL DEFAULT ''::text,
  modalidade text NOT NULL DEFAULT 'Presencial'::text,
  participantes_cliente text NOT NULL DEFAULT ''::text,
  dx_processos_descritos text NOT NULL DEFAULT ''::text,
  dx_processos_dores text NOT NULL DEFAULT ''::text,
  dx_processos_impacto text NOT NULL DEFAULT ''::text,
  dx_automacao_nivel text NOT NULL DEFAULT 'Nenhuma'::text,
  dx_automacao_gaps text NOT NULL DEFAULT ''::text,
  dx_integracao_sistemas text NOT NULL DEFAULT ''::text,
  dx_integracao_status text NOT NULL DEFAULT ''::text,
  dx_governanca_problemas text NOT NULL DEFAULT ''::text,
  dx_sponsor_engajamento text NOT NULL DEFAULT 'Médio'::text,
  hipotese_works text NOT NULL DEFAULT ''::text,
  escopo_preliminar text NOT NULL DEFAULT ''::text,
  objeccoes_levantadas text NOT NULL DEFAULT ''::text,
  proximo_passo_acordado text NOT NULL DEFAULT ''::text,
  data_proximo_passo text NOT NULL DEFAULT ''::text,
  fotos_evidencias ARRAY NOT NULL DEFAULT '{}'::text[],
  criado_em timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT visits_pkey PRIMARY KEY (id),
  CONSTRAINT visits_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES public.opportunities(id),
  CONSTRAINT visits_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT visits_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);